---
- name: "PRE-CHECK: Verify Architecture"
  ansible.builtin.set_fact:
    cms_pocketbase_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - unzip
      - ca-certificates
    state: present
    update_cache: true

- name: Create PocketBase group
  ansible.builtin.group:
    name: "{{ cms_pocketbase_group }}"
    state: present

- name: Create PocketBase user
  ansible.builtin.user:
    name: "{{ cms_pocketbase_user }}"
    group: "{{ cms_pocketbase_group }}"
    system: true
    shell: /usr/sbin/nologin

- name: Ensure install directory exists
  ansible.builtin.file:
    path: "{{ cms_pocketbase_bin_path }}"
    state: directory
    mode: '0755'

- name: Download and Unarchive PocketBase
  ansible.builtin.unarchive:
    src: >-
      https://github.com/pocketbase/pocketbase/releases/download/v{{ cms_pocketbase_version }}/pocketbase_{{ cms_pocketbase_version }}_linux_{{ cms_pocketbase_arch }}.zip
    dest: "{{ cms_pocketbase_bin_path }}"
    remote_src: true
    creates: "{{ cms_pocketbase_bin_path }}/pocketbase"
    owner: "{{ cms_pocketbase_user }}"
    group: "{{ cms_pocketbase_group }}"

- name: Ensure PocketBase directory ownership
  ansible.builtin.file:
    path: "{{ cms_pocketbase_data_path }}"
    owner: "{{ cms_pocketbase_user }}"
    group: "{{ cms_pocketbase_group }}"
    state: directory
    recurse: true

- name: Create Systemd service
  ansible.builtin.template:
    src: pocketbase.service.j2
    dest: /etc/systemd/system/pocketbase.service
    mode: '0644'
  notify: Reload Systemd

- name: Start PocketBase
  ansible.builtin.systemd:
    name: pocketbase
    state: started
    enabled: true
