---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: "Include cms_pocketbase"
      include_role:
        # We point one level up from molecule/default to find the role root
        name: "../../../cms_pocketbase"
