---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    published_ports:
      - 8090:8090/tcp
    command: /sbin/init
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - all
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      # Fixes the 'Unreachable' permission error on macOS
      remote_tmp: /tmp/ansible-remote
      local_tmp: /tmp/ansible-local
    ssh_connection:
      pipelining: True
verifier:
  name: ansible